version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
<<<<<<< HEAD
        container_name: pay-collet-app
=======
        container_name: ecommerce-app
>>>>>>> 40aebec (maincommit)
        volumes:
            - .:/var/www:cached
        networks:
            - laravel
        depends_on:
            - redis
        environment:
            - PHP_MEMORY_LIMIT=1024M

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:8000"
        volumes:
            - .:/var/www:rw  # Dosya izinlerini koru
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:5.7
<<<<<<< HEAD
        container_name: pay-collet-mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel-ecommerce
            MYSQL_USER: ecommerce-user
=======
        container_name: ecommerce-mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel-ecommerce
            MYSQL_USER: laravel-ecommerce
>>>>>>> 40aebec (maincommit)
            MYSQL_PASSWORD: 1
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:latest
<<<<<<< HEAD
        container_name: redis-container
=======
        container_name: ecommerce-redis-container
>>>>>>> 40aebec (maincommit)
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        networks:
            - laravel
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
